### ISSUE TITLE
Found a way how to get VUID key only using phone browser.

### ISSUE THREAD

**Issue by Arsyad1105** [weareblahs/unifi-tv#11]
I found a way to get VUID only using phone browser (chrome) but can try on other browser to see if it working.

Create new bookmark.
Name: Any names that easy
URL: Copy this `javascript:(function () {     var script =  document.createElement('script');    script.src="//cdn.jsdelivr.net/npm/eruda";     document.body.appendChild(script);    script.onload = function () {         eruda.init()     } })();`

Save on bookmark.

Then go to playtv.unifi.com.my and login like usual. After login press on URL tab and search [bookmark name]. Press on that bookmark and you can see there's little icon under your screen.

![Screenshot_20210626_171507](https://user-images.githubusercontent.com/65513499/123508443-19c02180-d6a2-11eb-8410-c3724c9b1f19.jpg)

Press it and inspect tab will shown. Go to resources and find VUID. Press it first before copy.

![Screenshot_20210626_165504](https://user-images.githubusercontent.com/65513499/123508492-699ee880-d6a2-11eb-91f7-df2d43330a2c.jpg)

**Comment by weareblahs** [comment]
Added new section that redirects to this page.

See [https://github.com/weareblahs/unifi-tv/blob/main/README.md#get-widevine-server-url-smartphone-by-using-google-chrome---credits-to-arsyad1105](https://github.com/weareblahs/unifi-tv/blob/main/README.md#get-widevine-server-url-smartphone-by-using-google-chrome---credits-to-arsyad1105).
