### ISSUE TITLE
Replace m3u8 streams from HTTP to HTTPS

### ISSUE THREAD

**Issue by samleong123** [weareblahs/unifi-tv#12]
Hi , i have some problem about the m3u8 stream on Microsoft Edge.
Not sure is the extension problem , i tried to install the extension you mentioned but it doesn't work 
It will stuck loading forever and i don't know what happened 
So i use Bitmovin Player to play it online : https://bitmovin.com/demos/stream-test
But it will required https DASH link instead of http
![image](https://user-images.githubusercontent.com/58818070/124370438-64e1c200-dcaa-11eb-8a28-6ec20baadbca.png)
and CORS error will be occured if we never install the [Bypass CORS extensions on Edge](https://chrome.google.com/webstore/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino) (It will shows ERROR_WIDEVINE_URL_EXCEPTION because the ottweb.hypp.tv have CORS policy that doesn't allow bitmovin.com to make a http request to their widevine server)

I find that if i replace the `http://1.9.62.158` in your unifi.ejs file to `https://web.hypp.tv` and it will work on Bitmovin Player
After replacing to https://web.hypp.tv it will redirect either to `https://pop5clustera00de07172379a62d6189.hypp.tv`
or `https://pop28clustera00de08172376d246317c.hypp.tv` which is using the same SSL cert with `https://web.hypp.tv`
so the URL will looks like : `https://web.hypp.tv/PLTV/88888888/224/3221227769/3221227769.mpd`

![image](https://user-images.githubusercontent.com/58818070/124370491-0b2dc780-dcab-11eb-9988-78272b04f7d6.png)

and it will be working on BitMovin player after replacing it to https + CORS unblock 
never tested on TiviMate yet , but should have no problem
![image](https://user-images.githubusercontent.com/58818070/124370504-1f71c480-dcab-11eb-820d-1d0dfd1b88f3.png)

**Comment by weareblahs** [comment]
I'll try replacing ``http://1.9.62.158`` to ``https://centerrrs.hypp.tv/`` - it works at my side.

**Comment by weareblahs** [comment]
Additionally, doing a reverse IP search of the current IP address that I'm using right now (1.9.62.158) returns no results.

**Comment by samleong123** [comment]
I found this playback URL from playtv website , when hit play they will query the playlink that will return https://web.hypp.tv/XXXXXX
and seems like their server for web.hypp.tv blocked ICMP request
![Screenshot 2021-07-04 at 16 09 30](https://user-images.githubusercontent.com/58818070/124378105-397ac980-dce2-11eb-9ce7-c81a7de6cb38.png)
and after redirected to pop*.hypp.tv , their server IP is different than web.hypp.tv and theres no blocking on ICMP request
![Screenshot 2021-07-04 at 16 08 10](https://user-images.githubusercontent.com/58818070/124378060-089a9480-dce2-11eb-9c31-b65c0f699240.png)

Its was working smoothly on the HTTP protocol of the IP address , just because i found that Microsoft Edge one hv some problem and i found out its work on HTTPS protocol with the domain name

just wonder will this domain name have rate limit or whatever that limit us to use this service

**Comment by weareblahs** [comment]
So, finding about the URL, that it has the full version of the URL (for example TV1):
``https://web.hypp.tv:443/PLTV/88888888/224/3221227769/3221227769.mpd?rrsip=web.hypp.tv:443&zoneoffset=0&servicetype=1&icpid=&accounttype=1&limitflux=-1&limitdur=-1&accountinfo=%2C10001001003072%2C42.153.141.73%2C20210708031625%2Curn:Huawei:liveTV:iptv243%2C10001001003072%2C-1%2C0%2C1%2C%2C%2C2%2CHESA0002%2C%2C%2C2%2C10000104067563%2C0%2C10000103443691%2C1118968526%2C%2C%2C2%2C1%2CEND&GuardEncType=2&it=H4sIAAAAAAAAADWOyw6CMBRE_6bLpi3vRVcYExODJqJbc2kvlVAotmji3yuK25k5kzN7ULjbSMaKPGl10xYqjTHiRYGRTvOcc46YNZoEvFdOCqLA2m40ldMLdjmVV84oo0JwGqWkXu62Fsy6rB5Dg15Gf-yE_tkplDq09AmBgjEeDcydG-nRwuvs7TohWK9qPBVJxuOciYQJMi9pDaH_NOQGoXTDBB713pkvIFuwAckEqgeDFQwox4e1P-7g9cfmDbv-8YL0AAAA&tenantId=6003``
which returns with an 404 error after a 302 redirect. I guess they put a rate limit on it. Any IP adresses which has HTTPS on their server?

**Comment by samleong123** [comment]
> https://web.hypp.tv:443/PLTV/88888888/224/3221227769/3221227769.mpd

I thinnk there's some problem on the query string 
if we remove the data all the way start from `?rrsip=web.hypp.tv:443&zoneoffset=0&servicetype=1&icpid=&accounttype=1&limitflux=-1&limitdur=-1&accountinfo=%2C10001001003072%2C42.153.141.73%2C20210708031625%2Curn:Huawei:liveTV:iptv243%2C10001001003072%2C-1%2C0%2C1%2C%2C%2C2%2CHESA0002%2C%2C%2C2%2C10000104067563%2C0%2C10000103443691%2C1118968526%2C%2C%2C2%2C1%2CEND&GuardEncType=2&it=H4sIAAAAAAAAADWOyw6CMBRE_6bLpi3vRVcYExODJqJbc2kvlVAotmji3yuK25k5kzN7ULjbSMaKPGl10xYqjTHiRYGRTvOcc46YNZoEvFdOCqLA2m40ldMLdjmVV84oo0JwGqWkXu62Fsy6rB5Dg15Gf-yE_tkplDq09AmBgjEeDcydG-nRwuvs7TohWK9qPBVJxuOciYQJMi9pDaH_NOQGoXTDBB713pkvIFuwAckEqgeDFQwox4e1P-7g9cfmDbv-8YL0AAAA&tenantId=6003`

and leave it like this only `https://web.hypp.tv/PLTV/88888888/224/3221227769/3221227769.mpd`

the link wont return 404 , instead of redirecting to *.hypp.tv , and giving the streamable link

and i guess they did put something rate limit on it , but for normal usage from different IP address should have no problem

but i guess they only allow Malaysia IP to visit `https://web.hypp.tv`
I tested with Taiwan IP , Residential network 
Unable to visit `https://web.hypp.tv` 
![image](https://user-images.githubusercontent.com/58818070/124858085-02593080-dfe0-11eb-8536-2126e9f31273.png)
![image](https://user-images.githubusercontent.com/58818070/124858088-038a5d80-dfe0-11eb-900f-93f72fb41854.png)

**Comment by weareblahs** [comment]
Although the ``web.hypp.tv`` link is geo-blocked, it did worked at my side.

Will be moving to TiviMate for testing later with the ``web.hypp.tv`` link.

**Comment by weareblahs** [comment]
Update: Just tested it on TiviMate and it worked normally.

Do you want me to update the unifitv.ejs file or give you the m3u8 file for testing?

**Comment by samleong123** [comment]
> Update: Just tested it on TiviMate and it worked normally.
> 
> Do you want me to update the unifitv.ejs file or give you the m3u8 file for testing first?

Its okay , if you tested working on my side it should be working (If not i will update here)
I will update the playlist on Tivimate once you publish the new unifitv.ejs file.
Will test later once you publish it.
Thanks!

**Comment by weareblahs** [comment]
Updated. Will take about 30 minutes to 2 hour to update for all users.

**Comment by samleong123** [comment]
> Updated. Will take about 30 minutes to 2 hour to update for all users.

I'll test after 1/2 hours 
I requested the backend server and it's still returning http://1.9.62.158/ (with F12 Disable Cache and different account)
CF Cache Cleared so it should be the cache on the backend server
