### ISSUE TITLE
Plans to add unifi TV VOD

### ISSUE THREAD

**Issue by weareblahs** [weareblahs/unifi-tv#14]
@ohsem @samleong123

Found out that unifi TV offers Snek, a free VOD platform can be used as VOD in TiviMate. Such as:
``https://playtv.unifi.com.my/EPG/WEBTV/index.html#/voddetail/VOD/49794158/Highlights%20/H4005`` - the MPD link is ``https://web.hypp.tv/88888888/16/20210602/268744907/268744907.mpd``

Basically everything is the same as the unifi TV one, but the EJS URL isn't the same - also, change the URL from /m3u8/unifi-tv to /m3u8/vod (or something like that) for this.

I'll collect these URLs soon.

**Comment by weareblahs** [comment]
Basically these links were accessible through the Widevine key process that we got using the Live TV process.

**Comment by samleong123** [comment]
I can do a seperate section for live tv and VOD on frontend 

For backend server , need to ask @ohsem wheter can the old nodejs script can work for this (replacing vuid i guess can right? basically same stuft)

**Comment by weareblahs** [comment]
and the URL for it too
After this, it will show up as https://unifiplaytv.samsam123.tk/vod/unifi-tv?username=xxxx&password=xxxx

**Comment by samleong123** [comment]
https://playtv.unifi.com.my/EPG/WEBTV/index.html#/voddetail/VOD/41757277/seasons

MPD : https://web.hypp.tv:443/88888888/16/20200306/268687800/268687800.mpd

**Comment by weareblahs** [comment]
Maybe we should use the old 1.9.2.158 for these VOD links.

**Comment by samleong123** [comment]
> Maybe we should use the old 1.9.2.158 for these VOD links.
> 
> Non-subscribers won't get access to links for MTV, Boomerang, BBC First and more, only Snek.

thats weird , even i get the playURL from their response (contain my ip addr and tenant id and so on) 
i will get 404 after redirected to pop*.hypp.tv
![image](https://user-images.githubusercontent.com/58818070/125197234-61909c80-e28f-11eb-8688-a1d0030e7397.png)


Update : 1.9.62.158 seems like can use
https://web.hypp.tv return 404 but 1.9.62.158 wont

**Comment by weareblahs** [comment]
if using web,hypp.tv through that one "native hls" player it will work sometimes

**Comment by weareblahs** [comment]
You can start finding the links, then I'll compile it and will make a test playlist for you all to test the VOD playlist on TiviMate.

**Comment by weareblahs** [comment]
Also, the links of the poster will be directly taken from playtv@unifi.

**Comment by samleong123** [comment]
> If using web,hypp.tv through that one "Native HLS" player, it will work sometimes.
for the direct IP link , for me it required PlayReady (Not sure why not widevine) , you can see its request to the RightManager.aspx
![image](https://user-images.githubusercontent.com/58818070/125197590-db755580-e290-11eb-9894-9e9a1258a046.png)

**Comment by weareblahs** [comment]
The MPD manifest is hybrid, as you can see, there's Widevine and PlayReady challenges in the DASH manifest.

**Comment by weareblahs** [comment]
> > If using web,hypp.tv through that one "Native HLS" player, it will work sometimes.
> 
> for the direct IP link , for me it required PlayReady (Not sure why not widevine) , you can see its request to the RightManager.aspx
> ![image](https://user-images.githubusercontent.com/58818070/125197590-db755580-e290-11eb-9894-9e9a1258a046.png)

But my Native HLS extension requires Widevine, not PlayReady.

That's odd.

**Comment by samleong123** [comment]
> > > If using web,hypp.tv through that one "Native HLS" player, it will work sometimes.
> > 
> > 
> > for the direct IP link , for me it required PlayReady (Not sure why not widevine) , you can see its request to the RightManager.aspx
> > ![image](https://user-images.githubusercontent.com/58818070/125197590-db755580-e290-11eb-9894-9e9a1258a046.png)
> 
> But my Native HLS extension requires Widevine, not PlayReady.
> 
> That's odd.

![image](https://user-images.githubusercontent.com/58818070/125198181-7111e480-e293-11eb-91b7-af01f48265f0.png)

i guess this is the one using playready , lemme disable it 
ps im using Edge

**Comment by samleong123** [comment]
![image](https://user-images.githubusercontent.com/58818070/125198255-b33b2600-e293-11eb-8d08-153d76654d88.png)

weird , 500 Internal Server Error on Widevine also

**Comment by weareblahs** [comment]
Try replacing https://web.hypp.tv to http://1.9.2.158. This extension supports HTTP Mixed Content.

**Comment by samleong123** [comment]
> Try replacing https://web.hypp.tv to http://1.9.62.158. This extension supports HTTP Mixed Content.
> 
> Use this for testing, but in TiviMate, we'll use web.hypp.tv.

weird , i tried the key for 8TV live tv its works , but until this : http://1.9.62.158/88888888/16/20200306/268687800/268687800.mpd

it wont work anymore , returning 500 on widevine server

**Comment by weareblahs** [comment]
![image](https://user-images.githubusercontent.com/37889443/125198704-a586a000-e295-11eb-8941-e11c68cb5d67.png)
...and it can play here. Now using Maxis Fibre Internet at other's house.

**Comment by samleong123** [comment]
> ![image](https://user-images.githubusercontent.com/37889443/125198776-de267980-e295-11eb-8461-dc2220eb8529.png)
> ...and it can play here. Now using Maxis Fibre Internet at other's house.

is it my luck or whatever i"ll have problem with the extension lol 🤣

**Comment by weareblahs** [comment]
You can try using Google Chrome.

**Comment by samleong123** [comment]
> You can try using Google Chrome.
> 
> Edge is a Chronium-based browser, so it will behave like Chrome.

so it should be same right 
im juz thinking is it something wrong on my side 
wheter is extension or whatever

**Comment by weareblahs** [comment]
Maybe that's the problem with unifi TV's WAF. You can try it using a different IP address.

**Comment by samleong123** [comment]
Thanks. I’ll try it 2moro , time for sleep😂

**Comment by weareblahs** [comment]
https://weareblahs.s-ul.eu/1skEprW1

Try putting this link on TiviMate and use VOD for this link. Contains both episodes of #TanyaSaya with 1.9.62.158 and web.hypp.tv, and Big Buck Bunny in MPD.

**Comment by samleong123** [comment]
> https://weareblahs.s-ul.eu/1skEprW1
> 
> Try putting this link on TiviMate and use VOD for this link. Contains both episodes of #TanyaSaya on both 1.9.62.158 and web.hypp.tv, and decrypted Big Buck Bunny in MPD taken from BBC R&D.
> 
> Tell me which server (web.hypp.tv or 1.9.62.158) is the best down below.
> 
> Googled it and still don't know how to put descriptions / categorize movies and tv shows.

the web.hypp.tv i keep getting 

`An error occurred.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the error log for details.

Faithfully yours, nginx.`

and it seems to be a 404

i tried disconnect pppoe and reconnect which give me another IP
still the same on web.hypp.tv

1.9.62.158 will be working on my side
(Its was working lah i can see the screen but DRM protected so black screen)

![image](https://user-images.githubusercontent.com/58818070/125213379-d17d4200-e2e4-11eb-842d-e1a35c0c2912.png)

**Comment by weareblahs** [comment]
Turns out that 1.9.62.158 seems to have no WAF, and mostly people will browse VOD content quickly through TiviMate.

My plan is to use web.hypp.tv on TiviMate as it uses ExoPlayer and unifi TV also uses ExoPlayer as their core.

**Comment by samleong123** [comment]
Deployed the modified version of @ohsem my-iptv , changed the ejs file to vod.ejs 
get it from here 

https://unifiplaytv.samsam123.tk/m3u8/unifi-tv?userID=`YourUserName`&clientPasswd=`YourPassword`

Replace `YourUserName` to your unifiPlayTV Username and `YourPassword` to your unifiPlayTV Password

**Comment by ohsem** [comment]
@weareblahs @samleong123 sorry I was a bit busy yesterday. I've deployed the VOD link to my heroku http://my-iptv.herokuapp.com/vod/unifi-tv?userID=`YourUserName`&clientPasswd=`YourPassword`.

I'm pulling the template from https://github.com/weareblahs/unifi-tv/blob/main/dev/vod.ejs 
Let me know if I can help with anything.

**Comment by samleong123** [comment]
fyi i redesign the home page already (with Live-TV and VOD)
it's look like this 


https://lh3.googleusercontent.com/fj7OIQTGrUHxDXnL4hUMqvWqkhuSE2ks6kTJ1EySC_hq_54623Jlf824DguZHAoRi1_zSEPsM62gu7GyRJgc3Ic4KnvKfudwYhqTyMEhmSoYmZ3wKGhrJrWbyiC0QD8w7V1tgb1921QrPGf1970pSzWmn9JdU9lePhO3O8diz0qHA0Juend5_QY1nZ8iYgcwI2tgKnoEATIRrFupT6G7Ptx1_Je0Ycb6gbfBbXNpwIsSzKOp8Gk8rBwul9gPw9qmSYGD265qHQqEOUmDwHb3daLXaYNiLEGvcsCwLFmX-TqYbQjXeovO44shkpJu6jqJheg-JC828auuprbBzVmyiyNAH6ko74ZLozk3m5VINNCS_VTTpzXXJdv_PpOZUZj8aaeqREwZFNoXpGgVPJJf3emJxEqDKwlsuwHl6KhS2CcXsCBl6PjAKqxS106IIMUqdXWhJx7dNMbd9oxseTy4mnK3A6JNLAKf3bx5sRY7uYK_X-f65-eSZcumZpaQJ5aZgAoK-Nr2kmiGszeSJ0BnUcdiJpTn1Se-amI6bKOYzPgurvP4bThsoZ12ofvUPA-YViQsqo85B8Anune2YElTTd1zatf-W4ZP3-2RZNvVfyxqM_4pvX0QMOpQaty4w3IFCznB0WXOeJSlBlh9YJwmklxUFOIv-uiCsdMHnm0q8g5LnjY8dofzb5QWNLjeBR-DyorGOoIXx_1WgNyLFRC7BKgDAQ=w1688-h914-no

https://lh3.googleusercontent.com/sRlkYDr0pjZPmkhgZXX7mEOUj4B4t0JMwhWOYuTWCrFsYU14B68hMHDTDu7yGJ_9B4IFm5xgo_dYqOBXQY2rMYw_PG5CTLqV2W8rnJih3IXJakJ4DIozlCS4ZBon_TLZRJPzWaJ1pIMGgkTLcHH9ymcJTY9wtaGqL1vz5BasIscIfjaUouUhLFGtkq1avi15V6SYEl9C0LuQehShG6R9DH2Uk5P5JN1UTpPZCPHs-xGs3ma7mHMWRc_y-lEqGk_dTAc_iKP4wjhCjqDjcfxlQk7r5lO7zlgQaje6kausgN83VZo-Yx6ND9OLPyUc-9Y9kBvGRbt5VqDHFsU0p5FH7t01sYzuKF0-jeoo0ItTRn61qB8CL-tqomkarVuDZccVH7hsIiqWsMUPTXdqSE4_-zUkhY-Y7l_3PiuhthpgD5PT_mprSXqq0n6VGSxjgHwemuWuKRHqk743rDta0xcqZEu1bssm6C_CPeRNDHiRt89ccgA3gMJjxtrZI_ciIsdrf6d1WhdG3g4Dkqmd_joZMhY8HgPLIAbLarm8Omk_VrDLMtYUUU9SYD1yahrC9thcSvgiggUofM7G69EyR29ClWlB1iBJAFE8i6weO2LfRY-Bt8GpO3aM2K1VANCmg4gp144S6fIgyP37ocoRUiTD-VM2-FpexkPmxNG4OBXc5mZTzcCJel7a17O6KzPfvtYPwNbjZOj6uyC2ffKiewT-HKVSjg=w1688-h914-no

**Comment by samleong123** [comment]
Not sure web.hypp.tv work or not , return 404 on my side
Below links are not tested , but it should work. (I just grab it and for the 1st MPD i tested stucked at decrypting audio , widevine server return 500 Error)

Air : https://playtv.unifi.com.my/EPG/WEBTV/index.html#/voddetail/VOD/49794158/Highlights%20/H4005

http://1.9.62.158/88888888/16/20210602/268744907/268744907.mpd

Alright then : https://playtv.unifi.com.my/EPG/WEBTV/index.html#/voddetail/VOD/49795444/Highlights%20/H4005

http://1.9.62.158/88888888/16/20210602/268744912/268744912.mpd

Balas : https://playtv.unifi.com.my/EPG/WEBTV/index.html#/voddetail/Snek/49795421/Highlights%20

http://1.9.62.158/88888888/16/20210602/268744894/268744894.mpd

Ban : https://playtv.unifi.com.my/EPG/WEBTV/index.html#/voddetail/VOD/49794155/Highlights%20/H4005

http://1.9.62.158/88888888/16/20210602/268744930/268744930.mpd

**Comment by weareblahs** [comment]
Added.

**Comment by weareblahs** [comment]
"Dirt" and "Hidden Gems" will be adding soon.

**Comment by weareblahs** [comment]
Added:
 - DW Try This! S01E01
 - DW Try This! S01E01
 - DW Try This! S01E01
 - DW Try This! S01E01
 - DW Try This! S01E01
 - DW Try This! S01E01
 - DW Try This! S01E01
 - DW Try This! S01E01
 - DW Try This! S01E01
 - DW Try This! S01E01
 - DW Try This! S01E01

**Comment by weareblahs** [comment]
Added:
 - DW Try This! S01E01
 - DW Try This! S01E02
 - DW Try This! S01E03
 - DW Try This! S01E04
 - DW Try This! S01E05
 - DW Try This! S01E06
 - DW Try This! S01E07
 - DW Try This! S01E08
 - DW Try This! S01E09
 - DW Try This! S01E10
 - DW Try This! S01E11
 - DW Try This! S01E12
 - DW Try This! S01E13
 - DW Try This! S01E14
 - DW Try This! S01E15

**Comment by weareblahs** [comment]
Is there any way that you can put descriptions on TiviMate? I suggested to the developer for the custom playlist syntax, but the developer responsed that they only support current M3U tags, not custom ones.

**Comment by samleong123** [comment]
> Is there any way that you can put descriptions on TiviMate? I suggested to the developer for the custom playlist syntax, but the developer responsed that they only support current M3U tags, not custom ones.

seems like Tivimate not support this yet , but maybe can supply a fake EPG as description? 

https://www.techkings.org/threads/vod-description-in-tivimate.150539/

**Comment by weareblahs** [comment]
I'll try making it soon and test it.

**Comment by samleong123** [comment]
VOD section added on frontend website.
![image](https://user-images.githubusercontent.com/58818070/125421840-a7cdef33-7246-44be-8904-6f13592a65ed.png)
![image](https://user-images.githubusercontent.com/58818070/125421848-86f0005f-4d18-4023-ac0f-eca74b374b0c.png)

**Comment by samleong123** [comment]
Drama 7 Petang Season1 
EP1 - EP12
https://playtv.unifi.com.my/EPG/WEBTV/index.html#/voddetail/VOD/41778986/seasons

EP1 : http://1.9.62.158/88888888/16/20200323/268690842/268690842.mpd
EP2 : http://1.9.62.158/88888888/16/20200323/268690839/268690839.mpd
EP3 : http://1.9.62.158/88888888/16/20200323/268691071/268691071.mpd
EP4 : http://1.9.62.158/88888888/16/20200325/268691296/268691296.mpd
EP5 : http://1.9.62.158/88888888/16/20200323/268691072/268691072.mpd
EP6 : http://1.9.62.158/88888888/16/20200323/268691068/268691068.mpd
EP7 : http://1.9.62.158/88888888/16/20200323/268691069/268691069.mpd
EP8 : http://1.9.62.158/88888888/16/20200323/268691059/268691059.mpd
EP9 : http://1.9.62.158/88888888/16/20200323/268691056/268691056.mpd
EP10 : http://1.9.62.158/88888888/16/20200323/268691060/268691060.mpd
EP11 : http://1.9.62.158/88888888/16/20200323/268691063/268691063.mpd
EP12 : http://1.9.62.158/88888888/16/20200323/268690833/268690833.mpd

**Comment by samleong123** [comment]
Hantu Tales Season 1
EP1 - EP 6
https://playtv.unifi.com.my/EPG/WEBTV/index.html#/voddetail/VOD/106519/LOL/H4004

EP1 : http://1.9.62.158/88888888/16/20200203/268680372/268680372.mpd
EP2 : http://1.9.62.158/88888888/16/20200203/268680578/268680578.mpd
EP3 : http://1.9.62.158/88888888/16/20200203/268680581/268680581.mpd
EP4 : http://1.9.62.158/88888888/16/20200203/268680658/268680658.mpd
EP5 : http://1.9.62.158/88888888/16/20200203/268680369/268680369.mpd
EP6 : http://1.9.62.158/88888888/16/20200203/268680649/268680649.mpd

**Comment by aa6my** [comment]
> Not sure web.hypp.tv work or not , return 404 on my side
> Below links are not tested , but it should work. (I just grab it and for the 1st MPD i tested stucked at decrypting audio , widevine server return 500 Error)
> 
> Air : https://playtv.unifi.com.my/EPG/WEBTV/index.html#/voddetail/VOD/49794158/Highlights%20/H4005
> 
> http://1.9.62.158/88888888/16/20210602/268744907/268744907.mpd
> 
> Alright then : https://playtv.unifi.com.my/EPG/WEBTV/index.html#/voddetail/VOD/49795444/Highlights%20/H4005
> 
> http://1.9.62.158/88888888/16/20210602/268744912/268744912.mpd
> 
> Balas : https://playtv.unifi.com.my/EPG/WEBTV/index.html#/voddetail/Snek/49795421/Highlights%20
> 
> http://1.9.62.158/88888888/16/20210602/268744894/268744894.mpd
> 
> Ban : https://playtv.unifi.com.my/EPG/WEBTV/index.html#/voddetail/VOD/49794155/Highlights%20/H4005
> 
> http://1.9.62.158/88888888/16/20210602/268744930/268744930.mpd

Based on sniffing need to execute access first to the link, and then you can access after that

```
Ref - http://1.9.62.158/88888888/16/20200203/268680372/268680372.mpd
```

```
POST http://1.9.58.117:7008/VSP/V3/PlayVOD?from=throughMSAAccess
{"checkLock":{"checkType":"0"},"mediaID":"40819184","seriesID":"106519","VODID":"106426"}=
```
