### ISSUE TITLE
TV1 and TV2

### ISSUE THREAD

**Issue by plastic3s** [weareblahs/unifi-tv#4]
**#Found Channel**

**TV1**
> ```
>   http://1.9.15.104/PLTV/88888888/224/3221227769/3221227769.mpd 
> ```

**TV2**
> ```
>   http://1.9.62.158/PLTV/88888888/224/3221227490/3221227490.mpd
> ```

**Comment by weareblahs** [comment]
These URLs are for an alternative server (1.9.15.104) rather than my playlist's server (1.9.62.158).

Thanks for these URLs, it will be used to start as an alternative server option soon (another file called unifi_alt.m3u8).

**Comment by weareblahs** [comment]
Changed the address from 1.9.62.158 to 1.9.15.104 to avoid redirection. The "3221227769" URL is also the new URL for TV1 as the original URL (3221227709) caused 404 errors to happen.

The 1.9.62.158 version can be found on https://github.com/weareblahs/unifi-tv/tree/main/alternative-playlists.
