### ISSUE TITLE
New Method to find the Widevine ID

### ISSUE THREAD

**Issue by samleong123** [weareblahs/unifi-tv#5]
![image](https://user-images.githubusercontent.com/58818070/118928811-4cc21780-b976-11eb-9e5c-28c233140de7.png)
https://playtv.unifi.com.my/EPG/WEBTV/index.html#/live-tv/guide
This link doesn't work for me , it will show error below
![image](https://user-images.githubusercontent.com/58818070/118928914-6e230380-b976-11eb-9b34-92988aad980a.png)
And i can't find the id in session storage 
![image](https://user-images.githubusercontent.com/58818070/118930508-6a907c00-b978-11eb-9c54-2abe9df042de.png)

I found another method but it will be a little bit confusing :
1. Visit https://playtv.unifi.com.my/EPG/WEBTV/index.html#/live-tv/
2. Login with ur unifi playtv account
3. Go to Inspectt Element - Application - Local Storage - https://playtv.unifi.com.my 
4. Find ```AuthResp_VUID``` which represent your Widevine Key in double quotes
Example : ```"xxxxx"```
![image](https://user-images.githubusercontent.com/58818070/118931351-76307280-b979-11eb-89cc-e336552d9e82.png)

5. Copy the value of ```AuthResp_VUID```
6. Replace the ```AuthResp_VUID``` to this url : 
```https://ottweb.hypp.tv:8064?deviceId=AuthResp_VUID```
Make sure to remove the double quotes so if ur ```AuthResp_VUID=x1234``` ur link will looks like this :
```https://ottweb.hypp.tv:8064?deviceId=x1234```

**Comment by weareblahs** [comment]
Instructions updated.

**Comment by weareblahs** [comment]
Script on [this page](https://github.com/weareblahs/unifi-tv/releases/tag/1.0_20210520) modified to use this method.
