### ISSUE TITLE
Upload playlist file to Google Drive for Direct Link Access

### ISSUE THREAD

**Issue by samleong123** [weareblahs/unifi-tv#6]
Usually Google Drive will provide a share link which is not the direct link for us to download the files
But we can get direct link access by this method to use it on supported players :
1. Upload the playlist file to Google Drive 
2. Share the file to Everyone and copy the link
![Screenshot 2021-06-07 at 14 21 04](https://user-images.githubusercontent.com/58818070/120969326-9dba7400-c79c-11eb-843a-5dffc1b73555.png)
![Screenshot 2021-06-07 at 14 21 14](https://user-images.githubusercontent.com/58818070/120969333-a01cce00-c79c-11eb-890b-7bc98d338631.png)
3. Get the file ID 
Example : 
![Screenshot 2021-06-07 at 14 23 02](https://user-images.githubusercontent.com/58818070/120969402-b32f9e00-c79c-11eb-8b26-4d40d9b17d2b.png)
4. Copy the file id and replace it into this link :
`https://drive.google.com/uc?id=[file_id]&export=download`
Replace the [file_id] with the file id copied just now
Example : 
File ID : 123456
Direct Link should be : `https://drive.google.com/uc?id=123456&export=download`
5. Copy the Direct Link replaced by file ID , paste it into TiviMate or others supported players and you can enjoy it now.
Example : 
![Screenshot 2021-06-07 at 14 23 23](https://user-images.githubusercontent.com/58818070/120969767-220cf700-c79d-11eb-9063-61422dd2928d.png)
![Screenshot 2021-06-07 at 14 24 21](https://user-images.githubusercontent.com/58818070/120969771-23d6ba80-c79d-11eb-96af-51e58d21d728.png)

**Comment by weareblahs** [comment]
Added Google Drive direct link mirror to README.md.

(If you still didn't know about it, the prebuilt playlist is actually on GitHub as unifi_prebuilt.m3u8)

Thanks for the suggestion!
