### ISSUE TITLE
new ip address

### ISSUE THREAD

**Issue by elhafizzo** [weareblahs/unifi-tv#9]
changed to 1.9.15.104

**Comment by weareblahs** [comment]
The IP address that I used (1.9.62.158) is redirecting to any other servers ranging from 1.9.15.100 to 1.9.15.109. 

When you go to ``http://1.9.62.158/PLTV/88888888/224/3221227769/3221227769.mpd``, it will be redirected to ``http://1.9.15.104/PLTV/88888888/224/3221227769/3221227769.mpd?icpid=88888888&from=0&hms_devid=1793,1601&online=1623649540``. Everytime you refresh, you will be taken to a new link ranging from 1.9.15.100 to 1.9.15.109.

**Comment by elhafizzo** [comment]
oic.. noted
